name: Live Endpoint Test

on:
  schedule:
    - cron: "30 12 * * *" # Run at 8:30 AM EST (Morning Rush Hour)
    - cron: "15 21 * * *" # Run at 5:15 PM EST (Evening Rust Hour)
    - cron: "00 07 * * *" # Run at 3:00 AM EST (Dead of the night)
  workflow_dispatch:

jobs:
  live-endpoint:
    name: Live Endpoint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Display Toolchain Information
        run: |
          cargo --version --verbose
          rustc --version

      - name: Live Endpoint Test
        run: |
          cargo check
          cargo test --verbose --test live_endpoint_canary
