on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

name: Create a PR on new GTFS release

jobs:
  check-gtfs-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Download Latest SEPTA GTFS Release
        id: gtfs-release
        uses: robinraju/release-downloader@v1.10
        with:
          repository: septadev/GTFS
          latest: true
          fileName: gtfs_public.zip

      - name: Unzip Artifacts and Copy
        run: |
          unzip gtfs_public.zip
          mv google_bus.zip ${{ github.workspace }}/tests/gtfs_data/septa_bus.zip
          mv google_rail.zip ${{ github.workspace }}/tests/gtfs_data/septa_rail.zip

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            tests/gtfs_data/septa_bus.zip
            tests/gtfs_data/septa_rail.zip
          title: GTFS Data Update to ${{steps.gtfs-release.outputs.tag_name}}
          body: Update SEPTA GTFS to ${{steps.gtfs-release.outputs.tag_name}}
          commit-message:
            Update SEPTA GTFS to ${{steps.gtfs-release.outputs.tag_name}}
          assignees: StefanBossbaly
          reviewers: StefanBossbaly
          branch: gtfs-update-to-${{steps.gtfs-release.outputs.tag_name}}
          delete-branch: true
          token: ${{ secrets.PAT_TOKEN }}
