on:
  push:
    tags:
      - "*"
  workflow_dispatch:

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CRATES_API_TOKEN }}
